from fastapi import FastAPI, HTTPException
from typing import Any, Dict, Optional
from jsonschema import Draft7Validator
from .schema_loader import load_schema
import uuid

app = FastAPI(title="Aether Graph Service", version="0.0.0")

# Load schemas (generated by packages/shared-types)
ENTITY_SCHEMA = load_schema("Entity")
RELATIONSHIP_SCHEMA = load_schema("Relationship")

entity_validator = Draft7Validator(ENTITY_SCHEMA)
relationship_validator = Draft7Validator(RELATIONSHIP_SCHEMA)

# TODO: replace with real DB/graph store
ENTITIES: Dict[str, Dict[str, Any]] = {}
RELATIONSHIPS: Dict[str, Dict[str, Any]] = {}


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/entities")
def create_entity(payload: Dict[str, Any]):
    errors = sorted(entity_validator.iter_errors(payload), key=lambda e: e.path)
    if errors:
        raise HTTPException(status_code=400, detail=[e.message for e in errors])

    entity_id = payload.get("id") or f"ent_{uuid.uuid4().hex}"
    payload["id"] = entity_id
    ENTITIES[entity_id] = payload
    return payload


@app.get("/entities/{id}")
def get_entity(id: str):
    entity = ENTITIES.get(id)
    if not entity:
        raise HTTPException(status_code=404, detail="Entity not found")
    return entity


@app.post("/relationships")
def create_relationship(payload: Dict[str, Any]):
    errors = sorted(relationship_validator.iter_errors(payload), key=lambda e: e.path)
    if errors:
        raise HTTPException(status_code=400, detail=[e.message for e in errors])

    rel_id = payload.get("id") or f"rel_{uuid.uuid4().hex}"
    payload["id"] = rel_id
    RELATIONSHIPS[rel_id] = payload
    return payload


@app.get("/relationships")
def list_relationships(
    fromEntityId: Optional[str] = None,
    toEntityId: Optional[str] = None,
    type: Optional[str] = None,
):
    items = list(RELATIONSHIPS.values())

    if fromEntityId:
        items = [r for r in items if r.get("fromEntityId") == fromEntityId]
    if toEntityId:
        items = [r for r in items if r.get("toEntityId") == toEntityId]
    if type:
        items = [r for r in items if r.get("type") == type]

    return {"relationships": items}
