from __future__ import annotations

from typing import Any, Optional, Protocol


class GraphBackend(Protocol):
    async def create_entity(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    async def get_entity(self, entity_id: str) -> Optional[dict[str, Any]]: ...

    async def upsert_canonical_content(self, entity_id: str, data: dict[str, Any]) -> dict[str, Any]: ...

    async def get_canonical_content(self, entity_id: str) -> Optional[dict[str, Any]]: ...

    async def create_source_document(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    async def list_source_documents(self, brand_id: str) -> list[dict[str, Any]]: ...

    async def list_source_documents_with_content(self, brand_id: str) -> list[dict[str, Any]]: ...

    async def create_relationship(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    async def list_relationships(
        self,
        *,
        from_entity_id: Optional[str] = None,
        to_entity_id: Optional[str] = None,
        rel_type: Optional[str] = None,
    ) -> list[dict[str, Any]]: ...

    async def get_neighbors(self, entity_id: str, relationship_types: Optional[list[str]] = None) -> list[dict[str, Any]]: ...

    async def get_brand_policy(self, brand_id: str) -> Optional[dict[str, Any]]: ...

    async def upsert_brand_policy(self, brand_id: str, policy: dict[str, Any]) -> dict[str, Any]: ...
